## Arrays in Numpy

#### Managing memory

In [1]:
import numpy as np
A = np.array([2, 7, 9], dtype = np.int8)
print(A)

[2 7 9]


#### Two dimensional array in numpy

In [4]:
B = np.array([
    [10, 30, 40],
    [34, 43, 25],
    [34, 67, 89],
])
B

array([[10, 30, 40],
       [34, 43, 25],
       [34, 67, 89]])

In [9]:
print(A[1])
print(B[1])
print(B[0][1])

7
[34 43 25]
30


#### Editing the elements of an array

In [12]:
A[0] = 45
B[0][1] = 67
B[2] = [ 1, 2, 3]
print (A)
print(B)

[45  7  9]
[[10 67 40]
 [34 43 25]
 [ 1  2  3]]


#### Basic operations on array

In [13]:
c = A.sum()
d = A.mean()
e = A.std()
f = B.sum(axis = 0)
g = B.std(axis = 1)
print(c)
print(d)
print(e)
print(f)
print(g)

61
20.333333333333332
17.46106780494506
[ 45 112  68]
[23.28089345  7.34846923  0.81649658]


#### Slicing an array

In [15]:
C = B[0:, :1]
print(C)

[[10]
 [34]
 [ 1]]


In [16]:
D = B[:1, 2:]
print(D)

[[40]]


#### Vectorized Operation

In [17]:
A + 2

array([47,  9, 11], dtype=int8)

In [18]:
print(A)

[45  7  9]


In [19]:
E =  B + 2
print(E)

[[12 69 42]
 [36 45 27]
 [ 3  4  5]]


In [20]:
A += 2
A

array([47,  9, 11], dtype=int8)

#### Array of evenly spaced values

In [22]:
F = np.arange(3, 20, 4)
F

array([ 3,  7, 11, 15, 19])

In [24]:
G = np.arange(5)
print(G)

[0 1 2 3 4]


In [26]:
H = np.arange(2, 6)
H

array([2, 3, 4, 5])